### ISSUE TITLE
Update demo app

### ISSUE THREAD

**Issue by jozsef-vesza** [jozsef-vesza/AVFoundation-Combine#12]
Instead of just printing values, the demo app should feature:
* a play/pause button (this would respond to changes in `rate`)
* a progress indicator (responding to changes in the playhead progress)

**Comment by jozsef-vesza** [comment]
Another consideration: Apple doesn't recommend subclassing `AVPlayerViewController` which I did in the demo app. I think that also should be changed to follow best practices.

**Comment by piterwilson** [comment]
Good point on the sub-classing. I see the recommendation from Apple but find no specific alternative for a custom UI playing in full-screen mode. 

After re-watching the best-practices session (https://developer.apple.com/videos/play/wwdc2019/503/) I am leaning to think the kind of presentation we want to use in this case is "inline" even though our "inline" presentation takes the whole screen. This makes use of the containment API.

I will have to adjust the code on PR #15
