### ISSUE TITLE
Add publisher for the player's `currentItem` property

### ISSUE THREAD

**Issue by jozsef-vesza** [jozsef-vesza/AVFoundation-Combine#4]
`AVPlayer`'s `currentItem` property can be nil, which is handled poorly by the current implementation:
```swift
func statusPublisher() -> AnyPublisher<AVPlayerItem.Status, Never> {
    guard let currentItem = currentItem else {
        return Empty().eraseToAnyPublisher()
    }
    let keyPath: KeyPath<AVPlayerItem, AVPlayerItem.Status> = \.status
    return Publishers.KVObservingPublisher(observedObject: currentItem, keyPath: keyPath).eraseToAnyPublisher()
}
```

As it only ever makes sense to observe the item's status if `playerItem` is not nil, it might be a good idea to introduce an additional publisher, which will fire when `playerItem` changes (since it's KVO-compliant according to the [docs](https://developer.apple.com/documentation/avfoundation/avplayer/1390806-replacecurrentitem))

**Comment by piterwilson** [comment]
👍 +1
